[package]
name = "maou_index"
version = "0.1.0"
edition = "2021"

[lib]
name = "maou_index"
crate-type = ["rlib"]

[dependencies]
pyo3 = { workspace = true }
pyo3-polars = { workspace = true }
polars = { workspace = true }
thiserror = { workspace = true }
